apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-checkout
  labels:
    app: team-checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-checkout
  template:
    metadata:
      labels:
        app: team-checkout
    spec:
      containers:
        - name: team-checkout
          image: team-checkout:v1
          env:
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: team-checkout
  labels:
    app: team-checkout
spec:
  selector:
    app: team-checkout
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 30003
  type: LoadBalancer
